# This file was generated by the AST generator. Do not edit.

from abc import ABC, abstractmethod
from typing import TypeVar, Generic

from .binary import Binary
from .grouping import Grouping
from .literal import Literal
from .unary import Unary

R = TypeVar('R')

class Expr(ABC):
    @abstractmethod
    def accept(self, visitor: 'ExprVisitor[R]') -> R:
        pass

class ExprVisitor(Generic[R], ABC):
    @abstractmethod
    def visit_binary(self, expr: 'Binary') -> R:
        pass

    @abstractmethod
    def visit_grouping(self, expr: 'Grouping') -> R:
        pass

    @abstractmethod
    def visit_literal(self, expr: 'Literal') -> R:
        pass

    @abstractmethod
    def visit_unary(self, expr: 'Unary') -> R:
        pass

__all__ = ['Binary', 'Grouping', 'Literal', 'Unary', 'Expr', 'ExprVisitor']
