# This file was generated by the AST generator. Do not edit.

from typing import TypeVar

from . import Token
from . import ExprVisitor
from . import Expr

R = TypeVar('R')

class Binary(Expr):
    left: Expr
    operator: Token
    right: Expr

    def accept(self, visitor: ExprVisitor[R]) -> R:
        return visitor.visit_binary(self)
