import os


def autogen_warning():
    return "# This file was generated by the AST generator. Do not edit."


def import_code(names: set[str]) -> str:
    KNOWN = {"Any": "from typing import Any"}
    imports = []
    for name in names:
        if name in KNOWN:
            imports.append(KNOWN[name])
        else:
            imports.append(f"from . import {name}")
    return "\n".join(imports)


def generate_init(outdir: str, class_names: list[str]):
    filename = f"{outdir}/__init__.py"

    imports = "\n".join(
        [
            f"from .{class_name.lower()} import {class_name}"
            for class_name in class_names
        ]
    )

    def _write_expr_interface(file):
        file.write("class Expr(ABC):\n")
        file.write("    @abstractmethod\n")
        file.write("    def accept(self, visitor: 'ExprVisitor[R]') -> R:\n")
        file.write("        pass\n")
        file.write("\n")

    def _write_expr_visitor(file, class_names: list[str]):
        file.write("class ExprVisitor(Generic[R], ABC):\n")
        for class_name in class_names:
            file.write("    @abstractmethod\n")
            file.write(
                f"    def visit_{class_name.lower()}(self, expr: '{class_name}') -> R:\n"
            )
            file.write("        pass\n")
            file.write("\n")

    all = ", ".join(
        [f"'{class_name}'" for class_name in class_names + ["Expr", "ExprVisitor"]]
    )

    with open(filename, "w") as file:
        file.write(f"{autogen_warning()}\n\n")
        file.write("from abc import ABC, abstractmethod\n")
        file.write("from typing import TypeVar, Generic\n")
        file.write("\n")
        file.write(f"{imports}\n\n")
        file.write("R = TypeVar('R')\n\n")
        _write_expr_interface(file)
        _write_expr_visitor(file, class_names)
        file.write(f"__all__ = [{all}]\n")


def generate_ast(outdir: str, parent: str, defs: list[str]):
    class_names = []
    for definition in defs:
        class_name, rest = definition.split(":")
        class_name, rest = class_name.strip(), rest.strip()

        class_names.append(class_name)
        attrs = []  # type, name
        for type_str in rest.split(","):
            attr_type, attr_name = type_str.strip().split(" ")
            attr_type, attr_name = attr_type.strip(), attr_name.strip()
            attrs.append((attr_type, attr_name))

        to_import = {parent, f"{parent}Visitor"} | set(attr[0] for attr in attrs)
        filename = f"{outdir}/{class_name.lower()}.py"

        with open(filename, "w") as file:
            file.write(f"{autogen_warning()}\n\n")
            file.write("from typing import TypeVar\n\n")
            file.write(f"{import_code(to_import)}\n\n")
            file.write("R = TypeVar('R')\n\n")
            file.write(f"class {class_name}({parent}):\n")
            for attr_type, attr_name in attrs:
                file.write(f"    {attr_name}: {attr_type}\n")
            file.write("\n")
            file.write("    def accept(self, visitor: ExprVisitor[R]) -> R:\n")
            file.write(f"        return visitor.visit_{class_name.lower()}(self)\n")

    generate_init(outdir, class_names)


# python ast/generate.py
if __name__ == "__main__":
    curr_dir = os.path.dirname(os.path.abspath(__file__))
    generate_ast(
        curr_dir,
        "Expr",
        [
            "Binary   : Expr left, Token operator, Expr right",
            "Grouping : Expr expression",
            "Literal  : Any value",
            "Unary    : Token operator, Expr right",
        ],
    )
