# This file was generated by the AST generator. Do not edit.

from typing import TypeVar

from . import ExprVisitor
from . import Expr

R = TypeVar('R')

class Grouping(Expr):
    expression: Expr

    def accept(self, visitor: ExprVisitor[R]) -> R:
        return visitor.visit_grouping(self)
