# This file was generated by the AST generator. Do not edit.

from typing import TypeVar

from . import ExprVisitor
from . import Expr
from typing import Any

R = TypeVar('R')

class Literal(Expr):
    value: Any

    def accept(self, visitor: ExprVisitor[R]) -> R:
        return visitor.visit_literal(self)
