# This file was generated by the AST generator. Do not edit.

from typing import TypeVar, TYPE_CHECKING

from .expr import Expr, ExprVisitor

if TYPE_CHECKING:
    from .. import Token

R = TypeVar('R')

class Binary(Expr):
    left: 'Expr'
    operator: 'Token'
    right: 'Expr'

    def __init__(self, left: 'Expr', operator: 'Token', right: 'Expr'):
        self.left = left
        self.operator = operator
        self.right = right

    def accept(self, visitor: 'ExprVisitor[R]') -> R:
        return visitor.visit_binary(self)
