# This file was generated by the AST generator. Do not edit.

from abc import ABC, abstractmethod
from typing import TypeVar, Generic, TYPE_CHECKING

if TYPE_CHECKING:
    from .binary import Binary
    from .grouping import Grouping
    from .literal import Literal
    from .unary import Unary
    from .. import Token

R = TypeVar("R")


class Expr(ABC):
    @abstractmethod
    def accept(self, visitor: "ExprVisitor[R]") -> R:
        pass


class ExprVisitor(Generic[R], ABC):
    @abstractmethod
    def visit_binary(self, expr: "Binary") -> R:
        pass

    @abstractmethod
    def visit_grouping(self, expr: "Grouping") -> R:
        pass

    @abstractmethod
    def visit_literal(self, expr: "Literal") -> R:
        pass

    @abstractmethod
    def visit_unary(self, expr: "Unary") -> R:
        pass

    @abstractmethod
    def visit_variable(self, expr: "Variable") -> R:
        pass


class Variable(Expr):
    def __init__(self, name: "Token"):
        self.name = name

    def accept(self, visitor: "ExprVisitor[R]") -> R:
        return visitor.visit_variable(self)
