# This file was generated by the AST generator. Do not edit.

from typing import TypeVar, TYPE_CHECKING

from .expr import Expr, ExprVisitor

R = TypeVar('R')

class Grouping(Expr):
    expression: 'Expr'

    def __init__(self, expression: 'Expr'):
        self.expression = expression

    def accept(self, visitor: 'ExprVisitor[R]') -> R:
        return visitor.visit_grouping(self)
