# This file was generated by the AST generator. Do not edit.

from typing import TypeVar, TYPE_CHECKING

from .expr import Expr, ExprVisitor

if TYPE_CHECKING:
    from typing import Any

R = TypeVar("R")


class Literal(Expr):
    value: "Any"

    def __init__(self, value: "Any"):
        self.value = value

    def accept(self, visitor: "ExprVisitor[R]") -> R:
        return visitor.visit_literal(self)
