# This file was generated by the AST generator. Do not edit.

from typing import TypeVar, TYPE_CHECKING

from .expr import Expr, ExprVisitor

if TYPE_CHECKING:
    from .. import Token

R = TypeVar("R")


class Unary(Expr):
    operator: "Token"
    right: "Expr"

    def __init__(self, operator: "Token", right: "Expr"):
        self.operator = operator
        self.right = right

    def accept(self, visitor: "ExprVisitor[R]") -> R:
        return visitor.visit_unary(self)
